---
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/luizribeiro/mariner/discussions
    about: Please ask and answer questions here.
  - name: Troubleshooting
    url: https://mariner.readthedocs.io/en/latest/troubleshooting.html
    about: >-
      Before filing an issue, please read the Troubleshooting section of
      the documentation.
